use springdb;

CREATE TABLE tbl_community (
  bno BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  content VARCHAR(2000) NOT NULL,
  writer VARCHAR(50) NOT NULL,

  regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  delflag BOOLEAN DEFAULT FALSE
);

select * from tbl_community;
